services:
  app:
    image: streamlit
    container_name: streamlit
    ports:
      - "8502:8502"
    networks:
      net:
#          ipv4_address: 172.22.22.10

networks:
  net:
    external: true
    
#    networks:
#      - default-network
#networks:
#  default-network:
#    driver: bridge
